"use server"

import { revalidatePath } from "next/cache"
import Anthropic from "@anthropic-ai/sdk"
import { createClient } from "@/lib/supabase/server"
import type { ServiceOffer, ServiceAddon, Currency, ServiceDeliverable, DeliverableCadence } from "@/lib/types"

const CADENCES: DeliverableCadence[] = ["once", "monthly", "quarterly", "biannual"]

function revalidateServices() {
  revalidatePath("/services")
}

// The form serializes its deliverable-list editor to JSON into a hidden
// "deliverables_json" field — no more relying on the user pressing Enter
// in a textarea to separate items.
function parseDeliverables(formData: FormData): ServiceDeliverable[] {
  const raw = (formData.get("deliverables_json") as string) ?? "[]"
  try {
    const parsed = JSON.parse(raw)
    if (!Array.isArray(parsed)) return []
    return parsed
      .map((d) => ({
        // The editor generates an id client-side for every line (including
        // ones loaded from before this field existed) — this is just a
        // server-side safety net in case one ever arrives missing.
        id: String(d?.id ?? "").trim() || crypto.randomUUID(),
        text: String(d?.text ?? "").trim(),
        cadence: (CADENCES as string[]).includes(d?.cadence) ? d.cadence as DeliverableCadence : "once",
        quantity: Number.isFinite(Number(d?.quantity)) && d?.quantity !== "" && d?.quantity != null ? Number(d.quantity) : null,
      }))
      .filter((d) => d.text)
  } catch {
    return []
  }
}

function parsePrice(formData: FormData): number | null {
  const raw = formData.get("price") as string
  if (!raw || raw.trim() === "") return null
  const n = Number(raw)
  return Number.isFinite(n) ? n : null
}

function parseCurrency(formData: FormData): Currency {
  return (formData.get("currency") as string) === "USD" ? "USD" : "MXN"
}

// ============================================================
// OFFERS
// ============================================================

export async function getServiceOffers(): Promise<ServiceOffer[]> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("service_offers")
    .select(`
      *,
      based_on_offer:service_offers!based_on_offer_id(id, name),
      default_project_type:project_types(id, name, color, icon),
      addons:service_offer_addons(addon:service_addons(*))
    `)
    .order("category")
    .order("is_base", { ascending: false })
    .order("name")
  if (error) throw error
  return (data ?? []).map((row) => ({
    ...row,
    addons: (row.addons ?? []).map((a: { addon: ServiceAddon }) => a.addon),
  })) as ServiceOffer[]
}

// ============================================================
// IMPORT / EXPORT — lets the catalog be generated by an AI outside this
// dashboard (no Anthropic tokens spent on this project's own autofill,
// suggestServiceOffer, one offer at a time) and pasted back in. References
// (based_on/default_project_type) travel as NAMES, not ids — ids from this
// database mean nothing to an external AI or a fresh import elsewhere.
// ============================================================

interface PortableDeliverable {
  text: string
  cadence: DeliverableCadence
  quantity: number | null
}

interface PortableOffer {
  category: string
  name: string
  description: string | null
  is_base: boolean
  based_on_offer_name: string | null
  default_project_type_name: string | null
  price: number | null
  currency: Currency
  price_note: string | null
  deliverables: PortableDeliverable[]
}

export async function exportServiceOffers(): Promise<string> {
  const offers = await getServiceOffers()
  const portable: PortableOffer[] = offers.map((o) => ({
    category: o.category,
    name: o.name,
    description: o.description,
    is_base: o.is_base,
    based_on_offer_name: o.based_on_offer?.name ?? null,
    default_project_type_name: o.default_project_type?.name ?? null,
    price: o.price,
    currency: o.currency,
    price_note: o.price_note,
    deliverables: o.deliverables.map((d) => ({ text: d.text, cadence: d.cadence, quantity: d.quantity })),
  }))
  return JSON.stringify({ offers: portable }, null, 2)
}

function parsePortableDeliverables(raw: unknown): ServiceDeliverable[] {
  if (!Array.isArray(raw)) return []
  return raw
    .map((d: Record<string, unknown>) => ({
      id: crypto.randomUUID(),
      text: String(d?.text ?? "").trim(),
      cadence: (CADENCES as string[]).includes(d?.cadence as string) ? (d.cadence as DeliverableCadence) : "once",
      quantity: Number.isFinite(Number(d?.quantity)) && d?.quantity !== "" && d?.quantity != null ? Number(d.quantity) : null,
    }))
    .filter((d) => d.text)
}

// Every offer in the JSON is always inserted as a brand-new row — never
// updates an existing offer, even if name+category match one already in
// the catalog. based_on_offer_name / default_project_type_name are resolved
// by exact case-insensitive name match against what already exists at
// import time; no match just leaves that reference null (reported as a
// warning, never blocks the import).
export async function importServiceOffers(json: string): Promise<{ offers: ServiceOffer[]; errors: string[] }> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  let parsed: { offers?: unknown[] }
  try {
    parsed = JSON.parse(json)
  } catch {
    return { offers: [], errors: ["JSON inválido — revisa que esté bien formado"] }
  }
  const rows = Array.isArray(parsed.offers) ? parsed.offers : []
  if (rows.length === 0) return { offers: [], errors: ["No se encontró un arreglo \"offers\" con contenido"] }

  const [existingOffers, existingTypes] = await Promise.all([
    supabase.from("service_offers").select("id, name"),
    supabase.from("project_types").select("id, name"),
  ])
  const offerByName = new Map((existingOffers.data ?? []).map((o) => [o.name.toLowerCase().trim(), o.id]))
  const typeByName = new Map((existingTypes.data ?? []).map((t) => [t.name.toLowerCase().trim(), t.id]))

  const created: ServiceOffer[] = []
  const errors: string[] = []

  for (const [i, raw] of rows.entries()) {
    const r = raw as Record<string, unknown>
    const name = String(r?.name ?? "").trim()
    const category = String(r?.category ?? "").trim()
    if (!name || !category) {
      errors.push(`Oferta #${i + 1}: falta "name" o "category" — se omitió`)
      continue
    }

    const basedOnName = String(r?.based_on_offer_name ?? "").trim()
    const basedOnId = basedOnName ? offerByName.get(basedOnName.toLowerCase()) ?? null : null
    if (basedOnName && !basedOnId) errors.push(`"${name}": no se encontró una oferta llamada "${basedOnName}" — se dejó sin oferta base`)

    const typeName = String(r?.default_project_type_name ?? "").trim()
    const typeId = typeName ? typeByName.get(typeName.toLowerCase()) ?? null : null
    if (typeName && !typeId) errors.push(`"${name}": no se encontró un tipo de proyecto llamado "${typeName}" — se dejó sin referencia`)

    const price = Number.isFinite(Number(r?.price)) && r?.price !== "" && r?.price != null ? Number(r.price) : null
    const currency: Currency = r?.currency === "USD" ? "USD" : "MXN"

    const { data, error } = await supabase
      .from("service_offers")
      .insert({
        category,
        name,
        description: r?.description ? String(r.description).trim() : null,
        deliverables: parsePortableDeliverables(r?.deliverables),
        is_base: !!r?.is_base,
        based_on_offer_id: basedOnId,
        default_project_type_id: typeId,
        price,
        currency,
        price_note: r?.price_note ? String(r.price_note).trim() : null,
        created_by: user?.id ?? null,
      })
      .select("*, based_on_offer:service_offers!based_on_offer_id(id, name), default_project_type:project_types(id, name, color, icon)")
      .single()

    if (error) {
      errors.push(`"${name}": ${error.message}`)
      continue
    }
    created.push({ ...data, addons: [] } as ServiceOffer)
    // A newly-created offer becomes eligible as a based_on target for later
    // rows in the same import batch.
    offerByName.set(name.toLowerCase(), data.id)
  }

  if (created.length > 0) revalidateServices()
  return { offers: created, errors }
}

export async function createServiceOffer(formData: FormData): Promise<ServiceOffer> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  const basedOnId = (formData.get("based_on_offer_id") as string) || null
  const projectTypeId = (formData.get("default_project_type_id") as string) || null

  const { data, error } = await supabase
    .from("service_offers")
    .insert({
      category:                formData.get("category") as string,
      name:                    formData.get("name") as string,
      description:             (formData.get("description") as string) || null,
      deliverables:            parseDeliverables(formData),
      is_base:                 formData.get("is_base") === "true",
      based_on_offer_id:       basedOnId,
      default_project_type_id: projectTypeId,
      price:                   parsePrice(formData),
      currency:                parseCurrency(formData),
      price_note:              (formData.get("price_note") as string) || null,
      created_by:              user?.id ?? null,
    })
    .select("*, based_on_offer:service_offers!based_on_offer_id(id, name), default_project_type:project_types(id, name, color, icon)")
    .single()
  if (error) throw error
  revalidateServices()
  return { ...data, addons: [] } as ServiceOffer
}

export async function updateServiceOffer(id: string, formData: FormData): Promise<ServiceOffer> {
  const supabase = await createClient()
  const basedOnId = (formData.get("based_on_offer_id") as string) || null
  const projectTypeId = (formData.get("default_project_type_id") as string) || null

  const { data, error } = await supabase
    .from("service_offers")
    .update({
      category:                formData.get("category") as string,
      name:                    formData.get("name") as string,
      description:             (formData.get("description") as string) || null,
      deliverables:            parseDeliverables(formData),
      is_base:                 formData.get("is_base") === "true",
      based_on_offer_id:       basedOnId,
      default_project_type_id: projectTypeId,
      price:                   parsePrice(formData),
      currency:                parseCurrency(formData),
      price_note:              (formData.get("price_note") as string) || null,
    })
    .eq("id", id)
    .select("*, based_on_offer:service_offers!based_on_offer_id(id, name), default_project_type:project_types(id, name, color, icon)")
    .single()
  if (error) throw error
  revalidateServices()
  return data as ServiceOffer
}

export async function archiveServiceOffer(id: string, archived: boolean): Promise<void> {
  const supabase = await createClient()
  const { error } = await supabase
    .from("service_offers")
    .update({ status: archived ? "archived" : "active" })
    .eq("id", id)
  if (error) throw error
  revalidateServices()
}

export async function deleteServiceOffer(id: string): Promise<void> {
  const supabase = await createClient()
  const { error } = await supabase.from("service_offers").delete().eq("id", id)
  if (error) throw error
  revalidateServices()
}

export async function setOfferAddons(offerId: string, addonIds: string[]): Promise<void> {
  const supabase = await createClient()
  const { error: delError } = await supabase.from("service_offer_addons").delete().eq("offer_id", offerId)
  if (delError) throw delError
  if (addonIds.length > 0) {
    const { error: insError } = await supabase
      .from("service_offer_addons")
      .insert(addonIds.map((addon_id) => ({ offer_id: offerId, addon_id })))
    if (insError) throw insError
  }
  revalidateServices()
}

// ============================================================
// ADDONS
// ============================================================

export async function getServiceAddons(): Promise<ServiceAddon[]> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("service_addons")
    .select("*")
    .order("name")
  if (error) throw error
  return (data ?? []) as ServiceAddon[]
}

export async function createServiceAddon(formData: FormData): Promise<ServiceAddon> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  const { data, error } = await supabase
    .from("service_addons")
    .insert({
      name:        formData.get("name") as string,
      description: (formData.get("description") as string) || null,
      price:       parsePrice(formData),
      currency:    parseCurrency(formData),
      price_note:  (formData.get("price_note") as string) || null,
      created_by:  user?.id ?? null,
    })
    .select()
    .single()
  if (error) throw error
  revalidateServices()
  return data as ServiceAddon
}

export async function updateServiceAddon(id: string, formData: FormData): Promise<ServiceAddon> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("service_addons")
    .update({
      name:        formData.get("name") as string,
      description: (formData.get("description") as string) || null,
      price:       parsePrice(formData),
      currency:    parseCurrency(formData),
      price_note:  (formData.get("price_note") as string) || null,
    })
    .eq("id", id)
    .select()
    .single()
  if (error) throw error
  revalidateServices()
  return data as ServiceAddon
}

export async function archiveServiceAddon(id: string, archived: boolean): Promise<void> {
  const supabase = await createClient()
  const { error } = await supabase
    .from("service_addons")
    .update({ status: archived ? "archived" : "active" })
    .eq("id", id)
  if (error) throw error
  revalidateServices()
}

export async function deleteServiceAddon(id: string): Promise<void> {
  const supabase = await createClient()
  const { error } = await supabase.from("service_addons").delete().eq("id", id)
  if (error) throw error
  revalidateServices()
}

// ============================================================
// AI AUTOFILL — one-shot, on demand. Fills description + deliverables
// (and suggests a project type) from category/name/hint the admin
// already typed. Never touches price, is_base, or based_on — those
// stay deliberate human calls, never a model's guess.
// ============================================================

export async function suggestServiceOffer(input: {
  category: string
  name: string
  hint?: string
  projectTypes: { id: string; name: string }[]
}): Promise<{ description: string; deliverables: ServiceDeliverable[]; project_type_id: string | null }> {
  if (!input.category.trim() || !input.name.trim()) {
    throw new Error("Escribe al menos la categoría y el nombre antes de autorrellenar")
  }
  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) throw new Error("ANTHROPIC_API_KEY no configurado")
  const client = new Anthropic({ apiKey })

  const typeList = input.projectTypes.map((t) => `- ${t.name} (id: ${t.id})`).join("\n") || "(sin tipos de proyecto registrados)"

  const msg = await client.messages.create({
    model: "claude-haiku-4-5-20251001",
    max_tokens: 500,
    messages: [{
      role: "user",
      content: `Eres estratega de una agencia de marketing/desarrollo armando su catálogo interno de servicios. Redacta una oferta de servicio a partir de estos datos:

Categoría: ${input.category}
Nombre de la oferta: ${input.name}
${input.hint?.trim() ? `Contexto adicional dado por el admin: ${input.hint.trim()}` : ""}

Escribe:
1. Una descripción corta (1-2 oraciones) que sea la promesa de valor de la oferta — qué resultado obtiene el cliente, no una lista de tareas.
2. Entre 3 y 7 entregables concretos y verificables (cosas que el cliente puede ver/recibir), cada uno una frase corta. Para cada uno decide su cadencia: "once" si es un entregable de una sola vez (ej. configuración inicial, auditoría de arranque), o "monthly"/"quarterly"/"biannual" si se repite con esa frecuencia (ej. reporte mensual, revisión trimestral de estrategia). Si no es obvio, usa "once".
3. De esta lista de tipos de proyecto ya existentes en el sistema, cuál (si alguno) es el más relevante para esta oferta — o null si ninguno aplica bien:
${typeList}

Responde ÚNICAMENTE con JSON válido (sin markdown, sin explicación):
{"description": "...", "deliverables": [{"text": "...", "cadence": "once"}, {"text": "...", "cadence": "monthly"}], "project_type_id": "<id o null>"}`,
    }],
  })

  const raw = (msg.content[0] as { type: string; text: string }).text.trim()
  const cleaned = raw.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "").trim()
  let parsed: { description?: string; deliverables?: { text?: string; cadence?: string }[]; project_type_id?: string | null }
  try {
    parsed = JSON.parse(cleaned)
  } catch {
    throw new Error("La IA no devolvió una respuesta válida — intenta de nuevo")
  }

  const validTypeId = input.projectTypes.some((t) => t.id === parsed.project_type_id) ? parsed.project_type_id! : null
  return {
    description: parsed.description?.trim() || "",
    // Quantity is deliberately never AI-guessed — same rule as price/is_base/
    // based_on, a contract number is a deliberate human call.
    deliverables: (parsed.deliverables ?? [])
      .map((d) => ({
        id: crypto.randomUUID(),
        text: (d.text ?? "").trim(),
        cadence: (CADENCES as string[]).includes(d.cadence ?? "") ? (d.cadence as DeliverableCadence) : "once",
        quantity: null,
      }))
      .filter((d) => d.text),
    project_type_id: validTypeId,
  }
}
